// ACTIONS FOR PRODUCT
export const GET_ALL_SPK_NOTA = "GET_ALL_SPK";
export const GET_SPK_NOTA = "GET_SPK_NOTA";
export const CREATE_SPK_NOTA = "CREATE_SPK_NOTA";
export const UPDATE_SPK_NOTA = "UPDATE_SPK_NOTA";
// export const PREVIEW_PROODUCT = "PREVIEW_PROODUCT";
export const CLEAR_SPK_NOTA = "CLEAR_SPK_NOTA";
export const SPK_NOTA_ERROR = "SPK_NOTA_ERROR";
export const DELETE_SPK_NOTA = "DELETE_SPK_NOTA";

// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const UPDATE_INFO_USERS = "UPDATE_INFO_USERS";
export const LOGOUT = "LOGOUT";
export const CLEAR = "CLEAR";
export const AUTH_ERROR = "AUTH_ERROR";

// ACTIONS FOR TRANSACTION
// export const GET_ALL_TR_SELLER = "GET_ALL_TR_SELLER";
// export const GET_ALL_TR_BUYER = "GET_ALL_TR_BUYER";
// export const CREATE_TR = "CREATE_TR";
// export const UPDATE_TR = "UPDATE_TR";

// ACTIONS FOR THEME
// export const UPDATE_THEME = "UPDATE_THEME";
